### ISSUE TITLE
Remote I/O error

### ISSUE THREAD

**Issue by bug-i** [corny/luftdaten-python#2]
I just installed everything like suggested on a clean actual raspbian, but I am receiving an I/O error when I am running main.py: 

pi@raspberrypi:~/luftdaten-python $ python3 main.py
Traceback (most recent call last):
File "main.py", line 30, in <module>
h_mode=BME280_OSAMPLE_8,
File "/home/pi/luftdaten-python/bme280/Adafruit_BME280.py", line 130, in __init__
self._load_calibration()
File "/home/pi/luftdaten-python/bme280/Adafruit_BME280.py", line 141, in _load_calibration
self.dig_T1 = self._device.readU16LE(BME280_REGISTER_DIG_T1)
File "/usr/local/lib/python3.5/dist-packages/Adafruit_GPIO-1.0.3-py3.5.egg/Adafruit_GPIO/I2C.py", line 187, in readU16LE
File "/usr/local/lib/python3.5/dist-packages/Adafruit_GPIO-1.0.3-py3.5.egg/Adafruit_GPIO/I2C.py", line 166, in readU16
File "/usr/local/lib/python3.5/dist-packages/Adafruit_PureIO-0.2.1-py3.5.egg/Adafruit_PureIO/smbus.py", line 173, in read_word_data
OSError: [Errno 121] Remote I/O error

any idea whats wrong? Thanks for your support!

**Comment by bug-i** [comment]
I think I found the reason. I have only the dust-sensor installed, not the Bosch-temperature sensor, which leads to the described error. Maybe you could add acheck and in the case of just only one sensor is installed submit the data of this sensor only instead of producing an error because of the missing second sensor.

**Comment by bug-i** [comment]
Error was caused by missing BME280 sensor
